# Etapa 1: build
FROM maven:3.9.8-eclipse-temurin-21 AS build
WORKDIR /code
COPY pom.xml .
RUN mvn -q -e -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -e -DskipTests package

# Etapa 2: runtime (fast-jar)
FROM eclipse-temurin:21-jre
WORKDIR /app

# copia a pasta quarkus-app inteira
COPY --from=build /code/target/quarkus-app/ /app/

# diretório para chaves (se você monta por volume)
RUN mkdir -p /app/jwt

EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/quarkus-run.jar"]
